# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: CI Pipeline - Teste e Build

# Gatilho (trigger): Quando este workflow deve rodar?
on:
  # Roda em todo push para a branch "main"
  push:
    branches: [ "main" ]
  # Roda em toda abertura ou atualização de Pull Request para a branch "main"
  pull_request:
    branches: [ "main" ]

# Jobs: Conjunto de tarefas a serem executadas
jobs:
  # Nome do nosso único job: build-and-test
  build-and-test:
    # Ambiente de execução: uma máquina virtual com a última versão do Ubuntu
    runs-on: ubuntu-latest

    # Passos (steps) que o job executará em sequência
    steps:
      # 1. Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Setup do Node.js
      - name: Setup do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Instalar dependências
      - name: Instalar dependências
        run: npm install

      # 4. DEBUG: Lista os arquivos para investigar o erro
      - name: DEBUG - Listar arquivos do projeto
        run: |
          echo "=================================================="
          echo "Procurando por qualquer arquivo com 'textarea' no nome..."
          find . -iname "*textarea*"
          echo "=================================================="

      # 5. Executar o Linter
      - name: Executar Linter
        run: npm run lint

      # 6. Executar o Build
      - name: Build do projeto
        run: npm run build